#wenxin:
#  api-key: bce-v3/ALTAK-vbJxvNZaMxVOVvBzP4Rmz/078325eea082b024e84aab85ffae44c199b32e51
#  secret-key: LnpsrANrzbz1RlkxXTfe44EmQgZxMZ2q
##千帆密钥配置
#qianfan:
#  access-key: "ALTAKNU2hLGRkkb8NjnIyq3Dfu"
#  secret-key: "26bcf3c7e5cc4fb581ec81a6b61f08a2"
#  model: "ERNIE-Bot-turbo"
#bos:
#  bucket-name: "pingpang"
## 文件上传配置
#file:
#  upload-dir: G:/localRepository/Pingpangtotal/uploads  # 修改为你想存储文件的路径
#upload:
#  path: G:/localRepository/Pingpangtotal/uploads # 设置文件上传路径
#
## 模型API接口地址
#model:
#  api:
#    url=http://your-model-api-url.com/processVideo
#
## 处理后视频存储的基础URL
#video:
#  storage:
#    url=http://your-bucket-url.com/processed_videos/
#
#
## Spring Boot 数据库配置（根据实际情况调整）
#spring:
#  servlet:
#    multipart:
#      location: G:\localRepository\Pingpangtotal\uploads
#      enabled: true
#      max-file-size: 50MB
#      max-request-size: 50MB
#  datasource:
#    url: jdbc:mysql://localhost:3306/pingpang?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Zhj5.3.8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#server:
#  port: 8888
#
#security:
#  basic:
#    enabled: false
#
#logging:
#  level:
#    root: INFO
#    org.example: DEBUG
#  file:
#    name: logs/application.log
wenxin:
  api-key: bce-v3/ALTAK-vbJxvNZaMxVOVvBzP4Rmz/078325eea082b024e84aab85ffae44c199b32e51
  secret-key: LnpsrANrzbz1RlkxXTfe44EmQgZxMZ2q


#千帆密钥配置
qianfan:
  access-key: "ALTAKNU2hLGRkkb8NjnIyq3Dfu"
  secret-key: "26bcf3c7e5cc4fb581ec81a6b61f08a2"
bos:
  bucket-name: "pingpang"
# 文件上传配置
file:
  upload-dir: F:/localRepository/Pingpangtotal/uploads  # 修改为你想存储文件的路径
upload:
  path: F:/localRepository/Pingpangtotal/uploads # 设置文件上传路径
# Spring Boot 数据库配置（根据实际情况调整）
spring:
  servlet:
    multipart:
      location: F:\localRepository\Pingpangtotal\uploads
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/pingpang?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Zhj5.3.8
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update  # 开发阶段自动更新表结构，生产环境建议使用 none 或手动管理
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8888

security:
  basic:
    enabled: false

logging:
  level:
    root: INFO
    org.example: DEBUG  # 让 org.example 这个包的日志级别更详细
  file:
    name: logs/application.log  # 指定日志文件路径
